# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-09 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_auto_20180808_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='income',
            name='budget',
        ),
    ]
